site_name: MCS nicotine puberty
theme:
  name: material
  palette:
    scheme: slate
  font:
    text: Inter
nav:
  - Home: index.md
  - Variables: variables.md
  - Files: files.md
markdown_extensions:
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
